// Generated by CoffeeScript 2.4.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    configmodule: require("./configmodule"),
    deploymenthandlermodule: require("./deploymenthandlermodule"),
    debugmodule: require("./debugmodule"),
    githubhandlermodule: require("./githubhandlermodule"),
    keymodule: require("./keymodule"),
    pathhandlermodule: require("./pathhandlermodule"),
    prepareprocessmodule: require("./prepareprocessmodule"),
    startupmodule: require("./startupmodule"),
    utilmodule: require("./utilmodule")
  };

  module.exports = Modules;

}).call(this);
