// Generated by CoffeeScript 2.5.1
(function() {
  var configmodule, err, homedir, log, os, packageJson, pathModule, userConfigModule, userConfigPath, userRelativeConfigPath;

  configmodule = {
    name: "configmodule"
  };

  //region modulesFromEnvironment
  pathModule = require("path");

  os = require("os");

  userConfigModule = null;

  //endregion

  //region exposedProperties
  configmodule.serverName = "default.server.tld";

  configmodule.name = "defaultName";

  configmodule.webhookSecret = "defaultSecret";

  configmodule.webhookPort = "3000";

  configmodule.webhookURL = "";

  configmodule.cli = {
    userRelativeConfigPath: ".config/thingyBubble/userConfig.json",
    userConfigPath: ""
  };

  //endregion

  //region pre-init
  //region getVersionAndName
  packageJson = require("./package.json");

  configmodule.cli.version = packageJson.version;

  configmodule.cli.name = packageJson.name;

  //endregion
  homedir = os.homedir();

  //region defineUserConfigPath§
  userRelativeConfigPath = configmodule.cli.userRelativeConfigPath;

  userConfigPath = pathModule.resolve(homedir, userRelativeConfigPath);

  configmodule.cli.userConfigPath = userConfigPath;

  //endregion
  configmodule.userConfig = null;

  try {
    configmodule.userConfig = require(configmodule.cli.userConfigPath);
  } catch (error) {
    err = error;
  }

  //endregion

  //region printLogFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["configmodule"] != null) {
      console.log("[configmodule]: " + arg);
    }
  };

  //endregion
  //#############################################################################
  configmodule.initialize = function() {
    log("configmodule.initialize");
    userConfigModule = allModules.userconfigmodule;
  };

  //region exposedFunctions
  configmodule.generateURL = function() {
    log("configmodule.genURL");
    configmodule.webhookURL = "https://";
    configmodule.webhookURL += configmodule.serverName;
    configmodule.webhookURL += ":";
    configmodule.webhookURL += configmodule.webhookPort;
    return configmodule.webhookURL += "/webhook";
  };

  configmodule.checkUserConfig = async function(configure) {
    log("configmodule.checkUserConfig");
    if (configmodule.userConfig) {
      await userConfigModule.checkProcess(configure);
    } else {
      await userConfigModule.userConfigurationProcess();
    }
  };

  //endregion
  module.exports = configmodule;

}).call(this);
