// Generated by CoffeeScript 2.5.1
(function() {
  var c, cliArguments, log, prepareProcess, startupmodule;

  startupmodule = {
    name: "startupmodule"
  };

  //region modulesFromEnvironment
  c = require("chalk");

  prepareProcess = null;

  cliArguments = null;

  //endregion

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["startupmodule"] != null) {
      console.log("[startupmodule]: " + arg);
    }
  };

  //endregion
  //#############################################################################
  startupmodule.initialize = function() {
    log("startupmodule.initialize");
    prepareProcess = allModules.prepareprocessmodule;
    cliArguments = allModules.cliargumentsmodule;
  };

  //region exposedFunctions
  startupmodule.cliStartup = async function() {
    var e, err;
    log("startupmodule.cliStartup");
    try {
      e = cliArguments.extractArguments();
      await prepareProcess.execute(e.keysDirectory, e.machineConfig, e.mode);
      console.log(c.green('All done!\n'));
    } catch (error) {
      err = error;
      console.log(c.red('Error!'));
      console.log(err);
      console.log("\n");
    }
  };

  //endregion
  module.exports = startupmodule;

}).call(this);
